[package]
name = "nievich331/ecoabad"
version = "0.1.0"
description = "Astro + Astrogon site on Wasmer"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "dist"

[[command]]
name = "web"
module = "wasmer/static-web-server:webserver"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--root", "/public"]
